version: "3.3"

services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
    - mode: ingress
      target: 8025
      published: "${MAILHOG_PUBLISHED_PORT:-8025}"
      protocol: tcp
    - mode: ingress
      target: 1025
      published: "1025"
      protocol: tcp
    labels:
      traefik.docker.network: traefik-public
      traefik.port: "{$MAILHOG_PUBLISHED_PORT:-8025}"
      traefik.enable: "true"
      traefik.http.routers.mailpit-http.entrypoints: http
      traefik.http.routers.mailpit-http.middlewares: https-redirect
      traefik.http.routers.mailpit-http.rule: Host(`${MAILHOG_HOSTNAME}`)
      traefik.http.routers.mailpit-http.service: mailpit
      traefik.http.routers.mailpit-https.entrypoints: https
      traefik.http.routers.mailpit-https.rule: Host(`${MAILHOG_HOSTNAME}`)
      traefik.http.routers.mailpit-https.service: mailpit
      traefik.http.routers.mailpit-https.tls: "true"
      traefik.http.routers.mailpit-https.tls.certresolver: le
      traefik.http.services.mailpit.loadbalancer.server.port: "8025"
    networks:
      - mailhog-network
      - traefik-public
    volumes:
    - type: volume
      source: mailpit-data
      target: /data
      volume: {}
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  mailhog-network:
    name: mailhog-network
    external: false
  traefik-public:
    name: traefik-public
    external: true

volumes:
  mailpit-data:
    name: mailpit-data
